// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Metadata of the column.
public struct ColumnMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Name of the column.
  public var column: Swift.String = Swift.String()

  /// Field path of the queried field, if any.
  public var fieldPath: Swift.String = Swift.String()

  /// Name of the function used to query the field, if any.
  public var functionName: Swift.String = Swift.String()

  /// Module of the function used to query the field, if any.
  public var functionModule: Swift.String = Swift.String()

  /// Data source queried.
  public var dataSource: DataSource = DataSource()

  /// Timestamp Metadata
  public var timestampMetadata: TimestampMetadata? = nil

  /// Whether the column is a longitude field.
  public var longitude: Swift.Bool = Swift.Bool()

  /// Whether the column is a latitude field.
  public var latitude: Swift.Bool = Swift.Bool()

  /// Whether the column is selected in the final response.
  public var selected: Swift.Bool = Swift.Bool()

  /// Whether the column is unselected in the final response.
  public var unselected: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `ColumnMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ColumnMetadata().with { $0.column = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.chronicle.v1.ColumnMetadata"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
