// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Pagination strategy for the request.
public struct CustomAPIPagination: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Select the specific paging mechanism the third-party API requires.
  public var paginationStrategy: OneOf_PaginationStrategy? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CustomAPIPagination`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CustomAPIPagination().with { $0.`none` = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let `none` = CodingKeys(stringValue: "none")
    static let token = CodingKeys(stringValue: "token")
    static let link = CodingKeys(stringValue: "link")
    static let offset = CodingKeys(stringValue: "offset")
    static let pageNumber = CodingKeys(stringValue: "pageNumber")

    static let _knownKeys: Set<Swift.String> = [
      "none",
      "token",
      "link",
      "offset",
      "pageNumber",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var paginationStrategy: OneOf_PaginationStrategy? = nil
    let paginationStrategyCheckAndSet = {
      if paginationStrategy != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'paginationStrategy'"))
      }
      paginationStrategy = $0
    }
    if let `none` = try container.decodeIfPresent(
      CustomAPIPagination.NonePagination?.self, forKey: .`none`)
    {
      try paginationStrategyCheckAndSet(.`none`(`none`))
    }
    if let token = try container.decodeIfPresent(
      CustomAPIPagination.TokenPagination?.self, forKey: .token)
    {
      try paginationStrategyCheckAndSet(.token(token))
    }
    if let link = try container.decodeIfPresent(
      CustomAPIPagination.LinkPagination?.self, forKey: .link)
    {
      try paginationStrategyCheckAndSet(.link(link))
    }
    if let offset = try container.decodeIfPresent(
      CustomAPIPagination.OffsetPagination?.self, forKey: .offset)
    {
      try paginationStrategyCheckAndSet(.offset(offset))
    }
    if let pageNumber = try container.decodeIfPresent(
      CustomAPIPagination.PageNumberPagination?.self, forKey: .pageNumber)
    {
      try paginationStrategyCheckAndSet(.pageNumber(pageNumber))
    }
    self.paginationStrategy = paginationStrategy
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.paginationStrategy {
      switch choice {
      case .`none`(let value):
        try container.encode(value, forKey: .`none`)
      case .token(let value):
        try container.encode(value, forKey: .token)
      case .link(let value):
        try container.encode(value, forKey: .link)
      case .offset(let value):
        try container.encode(value, forKey: .offset)
      case .pageNumber(let value):
        try container.encode(value, forKey: .pageNumber)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Fetch data in a single request without paging.
  public struct NonePagination: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `NonePagination`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = NonePagination().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let _knownKeys: Set<Swift.String> = []
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.chronicle.v1.CustomAPIPagination.NonePagination"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Use tokens (custom keys) to get the next page of data.
  public struct TokenPagination: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. Enter the field in the API response that contains the URL or
    /// token needed to fetch the next page of data.
    public var nextPageTokenJsonPath: Swift.String = Swift.String()

    /// Required. Specify the name of the query parameter for next page token in
    /// request.
    public var queryParam: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `TokenPagination`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TokenPagination().with { $0.nextPageTokenJsonPath = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let nextPageTokenJsonPath = CodingKeys(stringValue: "nextPageTokenJsonPath")
      static let queryParam = CodingKeys(stringValue: "queryParam")

      static let _knownKeys: Set<Swift.String> = [
        "nextPageTokenJsonPath",
        "queryParam",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        Swift.String.self, forKey: .nextPageTokenJsonPath)
      {
        self.nextPageTokenJsonPath = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .queryParam) {
        self.queryParam = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.nextPageTokenJsonPath, forKey: .nextPageTokenJsonPath)
      try container.encode(self.queryParam, forKey: .queryParam)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.chronicle.v1.CustomAPIPagination.TokenPagination"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Follow links provided in the response to get more data.
  public struct LinkPagination: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. Enter the field in the API response that contains the URL or
    /// token needed to fetch the next page of data.
    public var nextPageLinkJsonPath: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `LinkPagination`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = LinkPagination().with { $0.nextPageLinkJsonPath = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let nextPageLinkJsonPath = CodingKeys(stringValue: "nextPageLinkJsonPath")

      static let _knownKeys: Set<Swift.String> = [
        "nextPageLinkJsonPath"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nextPageLinkJsonPath)
      {
        self.nextPageLinkJsonPath = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.nextPageLinkJsonPath, forKey: .nextPageLinkJsonPath)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.chronicle.v1.CustomAPIPagination.LinkPagination"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Skip a set number of records to get the next set.
  public struct OffsetPagination: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. Specify the name of the query parameter for offset in request.
    public var offsetQueryParam: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `OffsetPagination`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = OffsetPagination().with { $0.offsetQueryParam = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let offsetQueryParam = CodingKeys(stringValue: "offsetQueryParam")

      static let _knownKeys: Set<Swift.String> = [
        "offsetQueryParam"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .offsetQueryParam) {
        self.offsetQueryParam = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.offsetQueryParam, forKey: .offsetQueryParam)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.chronicle.v1.CustomAPIPagination.OffsetPagination"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Go to the next page number (e.g., page 2).
  public struct PageNumberPagination: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. Specify the name of the query parameter for page number in
    /// request.
    public var pageNumberQueryParam: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PageNumberPagination`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PageNumberPagination().with { $0.pageNumberQueryParam = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let pageNumberQueryParam = CodingKeys(stringValue: "pageNumberQueryParam")

      static let _knownKeys: Set<Swift.String> = [
        "pageNumberQueryParam"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pageNumberQueryParam)
      {
        self.pageNumberQueryParam = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.pageNumberQueryParam, forKey: .pageNumberQueryParam)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.chronicle.v1.CustomAPIPagination.PageNumberPagination"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Select the specific paging mechanism the third-party API requires.
  public enum OneOf_PaginationStrategy: Codable, Equatable, Sendable {
    /// Fetch data in a single request without paging.
    indirect case `none`(CustomAPIPagination.NonePagination?)
    /// Use tokens (custom keys) to get the next page of data.
    indirect case token(CustomAPIPagination.TokenPagination?)
    /// Follow links provided in the response to get more data.
    indirect case link(CustomAPIPagination.LinkPagination?)
    /// Skip a set number of records to get the next set.
    indirect case offset(CustomAPIPagination.OffsetPagination?)
    /// Go to the next page number (e.g., page 2).
    indirect case pageNumber(CustomAPIPagination.PageNumberPagination?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.chronicle.v1.CustomAPIPagination"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
