// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Dashboard level filter that can be used in native dashboards as well as
/// inputs to execute query.
public struct DashboardFilter: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// ID of the filter.
  public var id: Swift.String = Swift.String()

  /// Datasource the filter is applicable for.
  public var dataSource: DataSource = DataSource()

  /// Filter field path.
  public var fieldPath: Swift.String = Swift.String()

  /// Operator and values. Can include multiple modifiers.
  public var filterOperatorAndFieldValues: [FilterOperatorAndValues] = []

  /// Display name of the filter.
  public var displayName: Swift.String = Swift.String()

  /// Chart IDs the filter is applicable for.
  public var chartIds: [Swift.String] = []

  /// Optional. Whether the filter is a standard time range filter,
  /// meaning that it has to be used as the query time range,
  /// and not as a predicate in the query.
  /// A chart can have at most one standard time range filter applied.
  public var isStandardTimeRangeFilter: Swift.Bool = Swift.Bool()

  /// Optional. Whether this filter is required to be populated by the
  /// dashboard consumer prior to the dashboard loading.
  public var isMandatory: Swift.Bool = Swift.Bool()

  /// Optional. Whether this standard time range filter is enabled.
  public var isStandardTimeRangeFilterEnabled: Swift.Bool? = nil

  /// Optional. Advanced filter configuration for the filter widget.
  public var advancedFilterConfig: AdvancedFilterConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DashboardFilter`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DashboardFilter().with { $0.id = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let id = CodingKeys(stringValue: "id")
    static let dataSource = CodingKeys(stringValue: "dataSource")
    static let fieldPath = CodingKeys(stringValue: "fieldPath")
    static let filterOperatorAndFieldValues = CodingKeys(
      stringValue: "filterOperatorAndFieldValues")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let chartIds = CodingKeys(stringValue: "chartIds")
    static let isStandardTimeRangeFilter = CodingKeys(stringValue: "isStandardTimeRangeFilter")
    static let isMandatory = CodingKeys(stringValue: "isMandatory")
    static let isStandardTimeRangeFilterEnabled = CodingKeys(
      stringValue: "isStandardTimeRangeFilterEnabled")
    static let advancedFilterConfig = CodingKeys(stringValue: "advancedFilterConfig")

    static let _knownKeys: Set<Swift.String> = [
      "id",
      "dataSource",
      "fieldPath",
      "filterOperatorAndFieldValues",
      "displayName",
      "chartIds",
      "isStandardTimeRangeFilter",
      "isMandatory",
      "isStandardTimeRangeFilterEnabled",
      "advancedFilterConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .id) {
      self.id = value
    }
    if let value = try container.decodeIfPresent(DataSource.self, forKey: .dataSource) {
      self.dataSource = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .fieldPath) {
      self.fieldPath = value
    }
    if let value = try container.decodeIfPresent(
      [FilterOperatorAndValues].self, forKey: .filterOperatorAndFieldValues)
    {
      self.filterOperatorAndFieldValues = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .chartIds) {
      self.chartIds = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .isStandardTimeRangeFilter)
    {
      self.isStandardTimeRangeFilter = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .isMandatory) {
      self.isMandatory = value
    }
    self.isStandardTimeRangeFilterEnabled = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .isStandardTimeRangeFilterEnabled)
    self.advancedFilterConfig = try container.decodeIfPresent(
      AdvancedFilterConfig.self, forKey: .advancedFilterConfig)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.id, forKey: .id)
    try container.encode(self.dataSource, forKey: .dataSource)
    try container.encode(self.fieldPath, forKey: .fieldPath)
    try container.encode(self.filterOperatorAndFieldValues, forKey: .filterOperatorAndFieldValues)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.chartIds, forKey: .chartIds)
    try container.encode(self.isStandardTimeRangeFilter, forKey: .isStandardTimeRangeFilter)
    try container.encode(self.isMandatory, forKey: .isMandatory)
    try container.encodeIfPresent(
      self.isStandardTimeRangeFilterEnabled, forKey: .isStandardTimeRangeFilterEnabled)
    try container.encodeIfPresent(self.advancedFilterConfig, forKey: .advancedFilterConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.chronicle.v1.DashboardFilter"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
