// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A DataAccessScope is a boolean expression of data access labels used
/// to restrict access to data for users.
public struct DataAccessScope: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The unique full name of the data access scope.
  /// The name should comply with https://google.aip.dev/122 standards.
  public var name: Swift.String = Swift.String()

  /// Optional. The allowed labels for the scope.
  /// Either allow_all or allowed_data_access_labels needs to be provided.
  /// When provided, there has to be at least one label allowed for the scope to
  /// be valid.
  /// The logical operator for evaluation of the allowed labels is OR.
  /// E.g.: A customer with scope with allowed labels A and B will be able
  /// to see data with labeled with A or B or (A and B).
  public var allowedDataAccessLabels: [DataAccessLabelReference] = []

  /// Optional. The denied labels for the scope.
  /// The logical operator for evaluation of the denied labels is AND.
  /// E.g.: A customer with scope with denied labels A and B won't be able
  /// to see data labeled with A and data labeled with B
  /// and data with labels A and B.
  public var deniedDataAccessLabels: [DataAccessLabelReference] = []

  /// Output only. The name to be used for display to customers of the data
  /// access scope.
  public var displayName: Swift.String = Swift.String()

  /// Output only. The time at which the data access scope was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time at which the data access scope was last updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The user who created the data access scope.
  public var author: Swift.String = Swift.String()

  /// Output only. The user who last updated the data access scope.
  public var lastEditor: Swift.String = Swift.String()

  /// Optional. A description of the data access scope for a human reader.
  public var description: Swift.String = Swift.String()

  /// Optional. Whether or not the scope allows all labels, allow_all and
  /// allowed_data_access_labels are mutually exclusive and one of them must be
  /// present. denied_data_access_labels can still be used along with allow_all.
  /// When combined with denied_data_access_labels, access will be granted to all
  /// data that doesn't have labels mentioned in denied_data_access_labels. E.g.:
  /// A customer with scope with denied labels A and B and allow_all will be able
  /// to see all data except data labeled with A and data labeled with B and data
  /// with labels A and B.
  public var allowAll: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `DataAccessScope`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataAccessScope().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.chronicle.v1.DataAccessScope"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
