// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A DataAccessLabel is a label on events to define user access to data.
public struct DataAccessLabel: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The unique resource name of the data access label.
  public var name: Swift.String = Swift.String()

  /// Output only. The short name displayed for the label as it appears on event
  /// data.
  public var displayName: Swift.String = Swift.String()

  /// Output only. The time at which the data access label was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The time at which the data access label was last updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The user who created the data access label.
  public var author: Swift.String = Swift.String()

  /// Output only. The user who last updated the data access label.
  public var lastEditor: Swift.String = Swift.String()

  /// Optional. A description of the data access label for a human reader.
  public var description: Swift.String = Swift.String()

  /// Required.
  /// The definition of the data access label that determines which
  /// data gets tagged with this label.
  public var definition: OneOf_Definition? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `DataAccessLabel`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataAccessLabel().with { $0.udmQuery = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let udmQuery = CodingKeys(stringValue: "udmQuery")
    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let author = CodingKeys(stringValue: "author")
    static let lastEditor = CodingKeys(stringValue: "lastEditor")
    static let description = CodingKeys(stringValue: "description")

    static let _knownKeys: Set<Swift.String> = [
      "udmQuery",
      "name",
      "displayName",
      "createTime",
      "updateTime",
      "author",
      "lastEditor",
      "description",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .author) {
      self.author = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .lastEditor) {
      self.lastEditor = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }

    var definition: OneOf_Definition? = nil
    let definitionCheckAndSet = {
      if definition != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'definition'"))
      }
      definition = $0
    }
    if let udmQuery = try container.decodeIfPresent(Swift.String.self, forKey: .udmQuery) {
      try definitionCheckAndSet(.udmQuery(udmQuery))
    }
    self.definition = definition
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.author, forKey: .author)
    try container.encode(self.lastEditor, forKey: .lastEditor)
    try container.encode(self.description, forKey: .description)

    if let choice = self.definition {
      switch choice {
      case .udmQuery(let value):
        try container.encode(value, forKey: .udmQuery)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Required.
  /// The definition of the data access label that determines which
  /// data gets tagged with this label.
  public enum OneOf_Definition: Codable, Equatable, Sendable {
    /// A UDM query over event data.
    case udmQuery(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.chronicle.v1.DataAccessLabel"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
