// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// DataTable represents the data table resource.
public struct DataTable: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the data table
  /// Format:
  /// "{project}/locations/{location}/instances/{instance}/dataTables/{data_table}"
  public var name: Swift.String = Swift.String()

  /// Output only. The unique display name of the data table.
  public var displayName: Swift.String = Swift.String()

  /// Required. A user-provided description of the data table.
  public var description: Swift.String = Swift.String()

  /// Output only. Table create time
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Table update time
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Immutable. Details of all the columns in the table
  public var columnInfo: [DataTableColumnInfo] = []

  /// Output only. Data table unique id
  public var dataTableUuid: Swift.String = Swift.String()

  /// Output only. The resource names for the associated Rules that use this
  /// data table. Format:
  /// projects/{project}/locations/{location}/instances/{instance}/rules/{rule}.
  /// {rule} here refers to the rule id.
  public var rules: [Swift.String] = []

  /// Output only. The count of rules using the data table.
  public var ruleAssociationsCount: Swift.Int32 = Swift.Int32()

  /// Optional. User-provided TTL of the data table.
  public var rowTimeToLive: Swift.String = Swift.String()

  /// Output only. The count of rows in the data table.
  public var approximateRowCount: Swift.Int64 = Swift.Int64()

  /// Optional. The scope info of the data table.
  /// During data table creation, if this field is not set, the data
  /// table without scopes (an unscoped table) will be created for a global
  /// user. For a scoped user, this field must be set. During data table
  /// update, if scope_info is requested to be updated, this field must be set.
  public var scopeInfo: DataTableScopeInfo? = nil

  /// Output only. Source of the data table update.
  public var updateSource: DataTableUpdateSource = DataTableUpdateSource()

  /// Output only. Last update time of the TTL of the data table.
  public var rowTimeToLiveUpdateTime: GoogleCloudWKT.Timestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `DataTable`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataTable().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let description = CodingKeys(stringValue: "description")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let columnInfo = CodingKeys(stringValue: "columnInfo")
    static let dataTableUuid = CodingKeys(stringValue: "dataTableUuid")
    static let rules = CodingKeys(stringValue: "rules")
    static let ruleAssociationsCount = CodingKeys(stringValue: "ruleAssociationsCount")
    static let rowTimeToLive = CodingKeys(stringValue: "rowTimeToLive")
    static let approximateRowCount = CodingKeys(stringValue: "approximateRowCount")
    static let scopeInfo = CodingKeys(stringValue: "scopeInfo")
    static let updateSource = CodingKeys(stringValue: "updateSource")
    static let rowTimeToLiveUpdateTime = CodingKeys(stringValue: "rowTimeToLiveUpdateTime")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "displayName",
      "description",
      "createTime",
      "updateTime",
      "columnInfo",
      "dataTableUuid",
      "rules",
      "ruleAssociationsCount",
      "rowTimeToLive",
      "approximateRowCount",
      "scopeInfo",
      "updateSource",
      "rowTimeToLiveUpdateTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([DataTableColumnInfo].self, forKey: .columnInfo) {
      self.columnInfo = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .dataTableUuid) {
      self.dataTableUuid = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .rules) {
      self.rules = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .ruleAssociationsCount) {
      self.ruleAssociationsCount = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .rowTimeToLive) {
      self.rowTimeToLive = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .approximateRowCount) {
      self.approximateRowCount = value
    }
    self.scopeInfo = try container.decodeIfPresent(DataTableScopeInfo.self, forKey: .scopeInfo)
    if let value = try container.decodeIfPresent(DataTableUpdateSource.self, forKey: .updateSource)
    {
      self.updateSource = value
    }
    self.rowTimeToLiveUpdateTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .rowTimeToLiveUpdateTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.description, forKey: .description)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.columnInfo, forKey: .columnInfo)
    try container.encode(self.dataTableUuid, forKey: .dataTableUuid)
    try container.encode(self.rules, forKey: .rules)
    try container.encode(self.ruleAssociationsCount, forKey: .ruleAssociationsCount)
    try container.encode(self.rowTimeToLive, forKey: .rowTimeToLive)
    try container.encode(self.approximateRowCount, forKey: .approximateRowCount)
    try container.encodeIfPresent(self.scopeInfo, forKey: .scopeInfo)
    try container.encode(self.updateSource, forKey: .updateSource)
    try container.encodeIfPresent(self.rowTimeToLiveUpdateTime, forKey: .rowTimeToLiveUpdateTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.chronicle.v1.DataTable"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
