// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleLongRunning
import GoogleWKT
import GoogleGax

extension Clients {
  protocol DataTableServiceStub: Sendable {
    func createDataTable(
      request: CreateDataTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.DataTable

    func listDataTables(
      request: ListDataTablesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.ListDataTablesResponse

    func getDataTable(
      request: GetDataTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.DataTable

    func updateDataTable(
      request: UpdateDataTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.DataTable

    func deleteDataTable(
      request: DeleteDataTableRequest, options: GoogleGax.RequestOptions
    ) async throws

    func createDataTableRow(
      request: CreateDataTableRowRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.DataTableRow

    func updateDataTableRow(
      request: UpdateDataTableRowRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.DataTableRow

    func listDataTableRows(
      request: ListDataTableRowsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.ListDataTableRowsResponse

    func getDataTableRow(
      request: GetDataTableRowRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.DataTableRow

    func deleteDataTableRow(
      request: DeleteDataTableRowRequest, options: GoogleGax.RequestOptions
    ) async throws

    func bulkCreateDataTableRows(
      request: BulkCreateDataTableRowsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.BulkCreateDataTableRowsResponse

    func bulkGetDataTableRows(
      request: BulkGetDataTableRowsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.BulkGetDataTableRowsResponse

    func bulkReplaceDataTableRows(
      request: BulkReplaceDataTableRowsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.BulkReplaceDataTableRowsResponse

    func bulkUpdateDataTableRows(
      request: BulkUpdateDataTableRowsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.BulkUpdateDataTableRowsResponse

    func getDataTableOperationErrors(
      request: GetDataTableOperationErrorsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.DataTableOperationErrors

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}
