// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleLongRunning
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class DataAccessControlServiceRetry: DataAccessControlServiceStub {
    let inner: any DataAccessControlServiceStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any DataAccessControlServiceStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func createDataAccessLabel(
      request: CreateDataAccessLabelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.DataAccessLabel {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateDataAccessLabelRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudChronicleV1.DataAccessLabel
          in
          return try await self.inner.createDataAccessLabel(request: r, options: o)
        })
    }

    public func getDataAccessLabel(
      request: GetDataAccessLabelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.DataAccessLabel {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetDataAccessLabelRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudChronicleV1.DataAccessLabel
          in
          return try await self.inner.getDataAccessLabel(request: r, options: o)
        })
    }

    public func listDataAccessLabels(
      request: ListDataAccessLabelsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.ListDataAccessLabelsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListDataAccessLabelsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudChronicleV1.ListDataAccessLabelsResponse
          in
          return try await self.inner.listDataAccessLabels(request: r, options: o)
        })
    }

    public func updateDataAccessLabel(
      request: UpdateDataAccessLabelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.DataAccessLabel {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateDataAccessLabelRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudChronicleV1.DataAccessLabel
          in
          return try await self.inner.updateDataAccessLabel(request: r, options: o)
        })
    }

    public func deleteDataAccessLabel(
      request: DeleteDataAccessLabelRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteDataAccessLabelRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteDataAccessLabel(request: r, options: o)
        })
    }

    public func createDataAccessScope(
      request: CreateDataAccessScopeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.DataAccessScope {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateDataAccessScopeRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudChronicleV1.DataAccessScope
          in
          return try await self.inner.createDataAccessScope(request: r, options: o)
        })
    }

    public func getDataAccessScope(
      request: GetDataAccessScopeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.DataAccessScope {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetDataAccessScopeRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudChronicleV1.DataAccessScope
          in
          return try await self.inner.getDataAccessScope(request: r, options: o)
        })
    }

    public func listDataAccessScopes(
      request: ListDataAccessScopesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.ListDataAccessScopesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListDataAccessScopesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudChronicleV1.ListDataAccessScopesResponse
          in
          return try await self.inner.listDataAccessScopes(request: r, options: o)
        })
    }

    public func updateDataAccessScope(
      request: UpdateDataAccessScopeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.DataAccessScope {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateDataAccessScopeRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudChronicleV1.DataAccessScope
          in
          return try await self.inner.updateDataAccessScope(request: r, options: o)
        })
    }

    public func deleteDataAccessScope(
      request: DeleteDataAccessScopeRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteDataAccessScopeRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteDataAccessScope(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
