// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message for the DeleteRule method.
public struct DeleteRuleRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The name of the rule to delete. A rule revision timestamp cannot
  /// be specified as part of the name, as deleting specific revisions is not
  /// supported.
  /// Format:
  /// `projects/{project}/locations/{location}/instances/{instance}/rules/{rule}`
  public var name: Swift.String = Swift.String()

  /// Optional. If set to true, any retrohunts and any detections associated with
  /// the rule will also be deleted. If set to false, the call will only succeed
  /// if the rule has no associated retrohunts, including completed retrohunts,
  /// and no associated detections. Regardless of this field's value, the rule
  /// deployment associated with this rule will also be deleted.
  public var force: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `DeleteRuleRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DeleteRuleRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.chronicle.v1.DeleteRuleRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
