// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleApi
import GoogleLongRunning
import GoogleWKT
import GoogleGax

/// FeedsService contains procedures for managing Chronicle third-party feeds.
///
/// @Snippet(path: "FeedsServiceQuickstart")
public final class FeedsServiceClient: Clients.FeedsServiceProtocol, Sendable {
  let inner: any Clients.FeedsServiceStub

  /// Creates a new `FeedsServiceClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.FeedsServiceStub = try Clients.FeedsServiceTransport(options)
    inner = Clients.FeedsServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.FeedsServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Fetch Chronicle's service account used for ingesting data from Cloud
  /// Storage buckets.
  ///
  /// @Snippet(path: "FeedsService_FetchServiceAccountForCustomer")
  public func fetchServiceAccountForCustomer(
    request: FetchServiceAccountForCustomerRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.FeedServiceAccount {
    try await self.inner.fetchServiceAccountForCustomer(request: request, options: options)
  }

  /// Creates a feed.
  ///
  /// @Snippet(path: "FeedsService_CreateFeed")
  public func createFeed(
    request: CreateFeedRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.Feed {
    try await self.inner.createFeed(request: request, options: options)
  }

  /// Gets a feed.
  ///
  /// @Snippet(path: "FeedsService_GetFeed")
  public func getFeed(
    request: GetFeedRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.Feed {
    try await self.inner.getFeed(request: request, options: options)
  }

  /// Deletes a feed.
  ///
  /// @Snippet(path: "FeedsService_DeleteFeed")
  public func deleteFeed(
    request: DeleteFeedRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteFeed(request: request, options: options)
  }

  /// Enable feed for ingestion.
  ///
  /// @Snippet(path: "FeedsService_EnableFeed")
  public func enableFeed(
    request: EnableFeedRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.Feed {
    try await self.inner.enableFeed(request: request, options: options)
  }

  /// Disable feed for ingestion. Make FeedState ARCHIVED.
  ///
  /// @Snippet(path: "FeedsService_DisableFeed")
  public func disableFeed(
    request: DisableFeedRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.Feed {
    try await self.inner.disableFeed(request: request, options: options)
  }

  /// Lists all feeds for the customer.
  ///
  /// @Snippet(path: "FeedsService_ListFeeds")
  public func listFeeds(
    request: ListFeedsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.ListFeedsResponse {
    try await self.inner.listFeeds(request: request, options: options)
  }

  /// Lists all feeds for the customer.
  ///
  /// @Snippet(path: "FeedsService_ListFeeds")
  public func listFeeds(
    byItem: ListFeedsRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<Feed, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudChronicleV1.ListFeedsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listFeeds(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Lists Packs for which feeds can be configured.
  ///
  /// @Snippet(path: "FeedsService_ListFeedPacks")
  public func listFeedPacks(
    request: ListFeedPacksRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.ListFeedPacksResponse {
    try await self.inner.listFeedPacks(request: request, options: options)
  }

  /// Lists Packs for which feeds can be configured.
  ///
  /// @Snippet(path: "FeedsService_ListFeedPacks")
  public func listFeedPacks(
    byItem: ListFeedPacksRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<FeedPack, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudChronicleV1.ListFeedPacksResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listFeedPacks(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets a feed pack.
  ///
  /// @Snippet(path: "FeedsService_GetFeedPack")
  public func getFeedPack(
    request: GetFeedPackRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.FeedPack {
    try await self.inner.getFeedPack(request: request, options: options)
  }

  /// Updates the full feed.
  ///
  /// @Snippet(path: "FeedsService_UpdateFeed")
  public func updateFeed(
    request: UpdateFeedRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.Feed {
    try await self.inner.updateFeed(request: request, options: options)
  }

  /// List all FeedSourceTypeSchemas.
  ///
  /// @Snippet(path: "FeedsService_ListFeedSourceTypeSchemas")
  public func listFeedSourceTypeSchemas(
    request: ListFeedSourceTypeSchemasRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.ListFeedSourceTypeSchemasResponse {
    try await self.inner.listFeedSourceTypeSchemas(request: request, options: options)
  }

  /// List all FeedSourceTypeSchemas.
  ///
  /// @Snippet(path: "FeedsService_ListFeedSourceTypeSchemas")
  public func listFeedSourceTypeSchemas(
    byItem: ListFeedSourceTypeSchemasRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<FeedSourceTypeSchema, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudChronicleV1.ListFeedSourceTypeSchemasResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listFeedSourceTypeSchemas(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// List all LogTypeSchemas compatible with a given
  /// FeedSourceType.
  ///
  /// @Snippet(path: "FeedsService_ListLogTypeSchemas")
  public func listLogTypeSchemas(
    request: ListLogTypeSchemasRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.ListLogTypeSchemasResponse {
    try await self.inner.listLogTypeSchemas(request: request, options: options)
  }

  /// List all LogTypeSchemas compatible with a given
  /// FeedSourceType.
  ///
  /// @Snippet(path: "FeedsService_ListLogTypeSchemas")
  public func listLogTypeSchemas(
    byItem: ListLogTypeSchemasRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<LogTypeSchema, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudChronicleV1.ListLogTypeSchemasResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLogTypeSchemas(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Import logs coming from https push feeds.
  /// All log entries must be valid UTF-8. A single invalid event will cause the
  /// entire request to be rejected.
  ///
  /// @Snippet(path: "FeedsService_ImportPushLogs")
  public func importPushLogs(
    request: ImportPushLogsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleApi.HttpBody {
    try await self.inner.importPushLogs(request: request, options: options)
  }

  /// Generates a new secret for https push feeds which do not support jwt
  /// tokens. Secrets once generated should be copied and stored in safe place
  /// to be used while configuring https push feeds.Please note that you can
  /// always generate a new secret again for a feed using this API but it will
  /// invalidate the previously generated secret for the feed.
  ///
  /// @Snippet(path: "FeedsService_GenerateSecret")
  public func generateSecret(
    request: GenerateSecretRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.GenerateSecretResponse {
    try await self.inner.generateSecret(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "FeedsService_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "FeedsService_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "FeedsService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "FeedsService_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "FeedsService_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `FeedsServiceClient`.
  ///
  /// To mock `FeedsServiceClient` change your functions to receive
  /// `some FeedsServiceProtocol` or `any FeedsServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol FeedsServiceProtocol {
    /// See `FeedsServiceClient.fetchServiceAccountForCustomer`.
    func fetchServiceAccountForCustomer(request: FetchServiceAccountForCustomerRequest) async throws
      -> GoogleCloudChronicleV1.FeedServiceAccount

    /// See `FeedsServiceClient.fetchServiceAccountForCustomer`.
    func fetchServiceAccountForCustomer(
      parent: Swift.String,
    ) async throws -> GoogleCloudChronicleV1.FeedServiceAccount

    /// See `FeedsServiceClient.createFeed`.
    func createFeed(request: CreateFeedRequest) async throws -> GoogleCloudChronicleV1.Feed

    /// See `FeedsServiceClient.createFeed`.
    func createFeed(
      parent: Swift.String,
      feed: Feed?,
    ) async throws -> GoogleCloudChronicleV1.Feed

    /// See `FeedsServiceClient.getFeed`.
    func getFeed(request: GetFeedRequest) async throws -> GoogleCloudChronicleV1.Feed

    /// See `FeedsServiceClient.getFeed`.
    func getFeed(
      name: Swift.String,
    ) async throws -> GoogleCloudChronicleV1.Feed

    /// See `FeedsServiceClient.deleteFeed`.
    func deleteFeed(request: DeleteFeedRequest) async throws

    /// See `FeedsServiceClient.deleteFeed`.
    func deleteFeed(
      name: Swift.String,
    ) async throws

    /// See `FeedsServiceClient.enableFeed`.
    func enableFeed(request: EnableFeedRequest) async throws -> GoogleCloudChronicleV1.Feed

    /// See `FeedsServiceClient.enableFeed`.
    func enableFeed(
      name: Swift.String,
    ) async throws -> GoogleCloudChronicleV1.Feed

    /// See `FeedsServiceClient.disableFeed`.
    func disableFeed(request: DisableFeedRequest) async throws -> GoogleCloudChronicleV1.Feed

    /// See `FeedsServiceClient.disableFeed`.
    func disableFeed(
      name: Swift.String,
    ) async throws -> GoogleCloudChronicleV1.Feed

    /// See `FeedsServiceClient.listFeeds`.
    func listFeeds(request: ListFeedsRequest) async throws
      -> GoogleCloudChronicleV1.ListFeedsResponse

    /// See `FeedsServiceClient.listFeeds`.
    func listFeeds(
      byItem: ListFeedsRequest
    ) throws -> any AsyncSequence<Feed, Swift.Error>

    /// See `FeedsServiceClient.listFeeds`.
    func listFeeds(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Feed, Swift.Error>

    /// See `FeedsServiceClient.listFeedPacks`.
    func listFeedPacks(request: ListFeedPacksRequest) async throws
      -> GoogleCloudChronicleV1.ListFeedPacksResponse

    /// See `FeedsServiceClient.listFeedPacks`.
    func listFeedPacks(
      byItem: ListFeedPacksRequest
    ) throws -> any AsyncSequence<FeedPack, Swift.Error>

    /// See `FeedsServiceClient.listFeedPacks`.
    func listFeedPacks(
      parent: Swift.String,
    ) throws -> any AsyncSequence<FeedPack, Swift.Error>

    /// See `FeedsServiceClient.getFeedPack`.
    func getFeedPack(request: GetFeedPackRequest) async throws -> GoogleCloudChronicleV1.FeedPack

    /// See `FeedsServiceClient.getFeedPack`.
    func getFeedPack(
      name: Swift.String,
    ) async throws -> GoogleCloudChronicleV1.FeedPack

    /// See `FeedsServiceClient.updateFeed`.
    func updateFeed(request: UpdateFeedRequest) async throws -> GoogleCloudChronicleV1.Feed

    /// See `FeedsServiceClient.updateFeed`.
    func updateFeed(
      feed: Feed?,
      updateMask: GoogleWKT.FieldMask?,
    ) async throws -> GoogleCloudChronicleV1.Feed

    /// See `FeedsServiceClient.listFeedSourceTypeSchemas`.
    func listFeedSourceTypeSchemas(request: ListFeedSourceTypeSchemasRequest) async throws
      -> GoogleCloudChronicleV1.ListFeedSourceTypeSchemasResponse

    /// See `FeedsServiceClient.listFeedSourceTypeSchemas`.
    func listFeedSourceTypeSchemas(
      byItem: ListFeedSourceTypeSchemasRequest
    ) throws -> any AsyncSequence<FeedSourceTypeSchema, Swift.Error>

    /// See `FeedsServiceClient.listFeedSourceTypeSchemas`.
    func listFeedSourceTypeSchemas(
      parent: Swift.String,
    ) throws -> any AsyncSequence<FeedSourceTypeSchema, Swift.Error>

    /// See `FeedsServiceClient.listLogTypeSchemas`.
    func listLogTypeSchemas(request: ListLogTypeSchemasRequest) async throws
      -> GoogleCloudChronicleV1.ListLogTypeSchemasResponse

    /// See `FeedsServiceClient.listLogTypeSchemas`.
    func listLogTypeSchemas(
      byItem: ListLogTypeSchemasRequest
    ) throws -> any AsyncSequence<LogTypeSchema, Swift.Error>

    /// See `FeedsServiceClient.listLogTypeSchemas`.
    func listLogTypeSchemas(
      parent: Swift.String,
    ) throws -> any AsyncSequence<LogTypeSchema, Swift.Error>

    /// See `FeedsServiceClient.importPushLogs`.
    func importPushLogs(request: ImportPushLogsRequest) async throws -> GoogleApi.HttpBody

    /// See `FeedsServiceClient.importPushLogs`.
    func importPushLogs(
      parent: Swift.String,
    ) async throws -> GoogleApi.HttpBody

    /// See `FeedsServiceClient.generateSecret`.
    func generateSecret(request: GenerateSecretRequest) async throws
      -> GoogleCloudChronicleV1.GenerateSecretResponse

    /// See `FeedsServiceClient.generateSecret`.
    func generateSecret(
      name: Swift.String,
    ) async throws -> GoogleCloudChronicleV1.GenerateSecretResponse

    /// See `FeedsServiceClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `FeedsServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `FeedsServiceClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `FeedsServiceClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `FeedsServiceClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `FeedsServiceClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `FeedsServiceClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `FeedsServiceClient.fetchServiceAccountForCustomer`.
    func fetchServiceAccountForCustomer(
      request: FetchServiceAccountForCustomerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.FeedServiceAccount

    /// See `FeedsServiceClient.createFeed`.
    func createFeed(
      request: CreateFeedRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.Feed

    /// See `FeedsServiceClient.getFeed`.
    func getFeed(
      request: GetFeedRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.Feed

    /// See `FeedsServiceClient.deleteFeed`.
    func deleteFeed(
      request: DeleteFeedRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `FeedsServiceClient.enableFeed`.
    func enableFeed(
      request: EnableFeedRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.Feed

    /// See `FeedsServiceClient.disableFeed`.
    func disableFeed(
      request: DisableFeedRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.Feed

    /// See `FeedsServiceClient.listFeeds`.
    func listFeeds(
      request: ListFeedsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.ListFeedsResponse

    /// See `FeedsServiceClient.listFeeds`.
    func listFeeds(
      byItem: ListFeedsRequest, options: GoogleGax.RequestOptions
    ) throws -> any AsyncSequence<Feed, Swift.Error>

    /// See `FeedsServiceClient.listFeedPacks`.
    func listFeedPacks(
      request: ListFeedPacksRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.ListFeedPacksResponse

    /// See `FeedsServiceClient.listFeedPacks`.
    func listFeedPacks(
      byItem: ListFeedPacksRequest, options: GoogleGax.RequestOptions
    ) throws -> any AsyncSequence<FeedPack, Swift.Error>

    /// See `FeedsServiceClient.getFeedPack`.
    func getFeedPack(
      request: GetFeedPackRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.FeedPack

    /// See `FeedsServiceClient.updateFeed`.
    func updateFeed(
      request: UpdateFeedRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.Feed

    /// See `FeedsServiceClient.listFeedSourceTypeSchemas`.
    func listFeedSourceTypeSchemas(
      request: ListFeedSourceTypeSchemasRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.ListFeedSourceTypeSchemasResponse

    /// See `FeedsServiceClient.listFeedSourceTypeSchemas`.
    func listFeedSourceTypeSchemas(
      byItem: ListFeedSourceTypeSchemasRequest, options: GoogleGax.RequestOptions
    ) throws -> any AsyncSequence<FeedSourceTypeSchema, Swift.Error>

    /// See `FeedsServiceClient.listLogTypeSchemas`.
    func listLogTypeSchemas(
      request: ListLogTypeSchemasRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.ListLogTypeSchemasResponse

    /// See `FeedsServiceClient.listLogTypeSchemas`.
    func listLogTypeSchemas(
      byItem: ListLogTypeSchemasRequest, options: GoogleGax.RequestOptions
    ) throws -> any AsyncSequence<LogTypeSchema, Swift.Error>

    /// See `FeedsServiceClient.importPushLogs`.
    func importPushLogs(
      request: ImportPushLogsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody

    /// See `FeedsServiceClient.generateSecret`.
    func generateSecret(
      request: GenerateSecretRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.GenerateSecretResponse

    /// See `FeedsServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `FeedsServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `FeedsServiceClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `FeedsServiceClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.FeedsServiceProtocol {
  public func fetchServiceAccountForCustomer(request: FetchServiceAccountForCustomerRequest)
    async throws -> GoogleCloudChronicleV1.FeedServiceAccount
  {
    try await self.fetchServiceAccountForCustomer(request: request, options: .init())
  }

  public func fetchServiceAccountForCustomer(
    request: FetchServiceAccountForCustomerRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.FeedServiceAccount {
    throw GoogleGax.RequestError.unimplemented
  }

  public func fetchServiceAccountForCustomer(
    parent: Swift.String,
  ) async throws -> GoogleCloudChronicleV1.FeedServiceAccount {
    let request = FetchServiceAccountForCustomerRequest().with {
      $0.parent = parent
    }
    return try await self.fetchServiceAccountForCustomer(request: request)
  }

  public func createFeed(request: CreateFeedRequest) async throws -> GoogleCloudChronicleV1.Feed {
    try await self.createFeed(request: request, options: .init())
  }

  public func createFeed(
    request: CreateFeedRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.Feed {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createFeed(
    parent: Swift.String,
    feed: Feed?,
  ) async throws -> GoogleCloudChronicleV1.Feed {
    let request = CreateFeedRequest().with {
      $0.parent = parent
      $0.feed = feed
    }
    return try await self.createFeed(request: request)
  }

  public func getFeed(request: GetFeedRequest) async throws -> GoogleCloudChronicleV1.Feed {
    try await self.getFeed(request: request, options: .init())
  }

  public func getFeed(
    request: GetFeedRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.Feed {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getFeed(
    name: Swift.String,
  ) async throws -> GoogleCloudChronicleV1.Feed {
    let request = GetFeedRequest().with {
      $0.name = name
    }
    return try await self.getFeed(request: request)
  }

  public func deleteFeed(request: DeleteFeedRequest) async throws {
    try await self.deleteFeed(request: request, options: .init())
  }

  public func deleteFeed(
    request: DeleteFeedRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteFeed(
    name: Swift.String,
  ) async throws {
    let request = DeleteFeedRequest().with {
      $0.name = name
    }
    try await self.deleteFeed(request: request)
  }

  public func enableFeed(request: EnableFeedRequest) async throws -> GoogleCloudChronicleV1.Feed {
    try await self.enableFeed(request: request, options: .init())
  }

  public func enableFeed(
    request: EnableFeedRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.Feed {
    throw GoogleGax.RequestError.unimplemented
  }

  public func enableFeed(
    name: Swift.String,
  ) async throws -> GoogleCloudChronicleV1.Feed {
    let request = EnableFeedRequest().with {
      $0.name = name
    }
    return try await self.enableFeed(request: request)
  }

  public func disableFeed(request: DisableFeedRequest) async throws -> GoogleCloudChronicleV1.Feed {
    try await self.disableFeed(request: request, options: .init())
  }

  public func disableFeed(
    request: DisableFeedRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.Feed {
    throw GoogleGax.RequestError.unimplemented
  }

  public func disableFeed(
    name: Swift.String,
  ) async throws -> GoogleCloudChronicleV1.Feed {
    let request = DisableFeedRequest().with {
      $0.name = name
    }
    return try await self.disableFeed(request: request)
  }

  public func listFeeds(request: ListFeedsRequest) async throws
    -> GoogleCloudChronicleV1.ListFeedsResponse
  {
    try await self.listFeeds(request: request, options: .init())
  }

  public func listFeeds(
    request: ListFeedsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.ListFeedsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listFeeds(
    byItem: ListFeedsRequest
  ) throws -> any AsyncSequence<Feed, Swift.Error> {
    try self.listFeeds(byItem: byItem, options: .init())
  }

  public func listFeeds(
    byItem: ListFeedsRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<Feed, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudChronicleV1.ListFeedsResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listFeeds(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Feed, Swift.Error> {
    let request = ListFeedsRequest().with {
      $0.parent = parent
    }
    return try self.listFeeds(byItem: request)
  }

  public func listFeedPacks(request: ListFeedPacksRequest) async throws
    -> GoogleCloudChronicleV1.ListFeedPacksResponse
  {
    try await self.listFeedPacks(request: request, options: .init())
  }

  public func listFeedPacks(
    request: ListFeedPacksRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.ListFeedPacksResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listFeedPacks(
    byItem: ListFeedPacksRequest
  ) throws -> any AsyncSequence<FeedPack, Swift.Error> {
    try self.listFeedPacks(byItem: byItem, options: .init())
  }

  public func listFeedPacks(
    byItem: ListFeedPacksRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<FeedPack, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudChronicleV1.ListFeedPacksResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listFeedPacks(
    parent: Swift.String,
  ) throws -> any AsyncSequence<FeedPack, Swift.Error> {
    let request = ListFeedPacksRequest().with {
      $0.parent = parent
    }
    return try self.listFeedPacks(byItem: request)
  }

  public func getFeedPack(request: GetFeedPackRequest) async throws
    -> GoogleCloudChronicleV1.FeedPack
  {
    try await self.getFeedPack(request: request, options: .init())
  }

  public func getFeedPack(
    request: GetFeedPackRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.FeedPack {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getFeedPack(
    name: Swift.String,
  ) async throws -> GoogleCloudChronicleV1.FeedPack {
    let request = GetFeedPackRequest().with {
      $0.name = name
    }
    return try await self.getFeedPack(request: request)
  }

  public func updateFeed(request: UpdateFeedRequest) async throws -> GoogleCloudChronicleV1.Feed {
    try await self.updateFeed(request: request, options: .init())
  }

  public func updateFeed(
    request: UpdateFeedRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.Feed {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateFeed(
    feed: Feed?,
    updateMask: GoogleWKT.FieldMask?,
  ) async throws -> GoogleCloudChronicleV1.Feed {
    let request = UpdateFeedRequest().with {
      $0.feed = feed
      $0.updateMask = updateMask
    }
    return try await self.updateFeed(request: request)
  }

  public func listFeedSourceTypeSchemas(request: ListFeedSourceTypeSchemasRequest) async throws
    -> GoogleCloudChronicleV1.ListFeedSourceTypeSchemasResponse
  {
    try await self.listFeedSourceTypeSchemas(request: request, options: .init())
  }

  public func listFeedSourceTypeSchemas(
    request: ListFeedSourceTypeSchemasRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.ListFeedSourceTypeSchemasResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listFeedSourceTypeSchemas(
    byItem: ListFeedSourceTypeSchemasRequest
  ) throws -> any AsyncSequence<FeedSourceTypeSchema, Swift.Error> {
    try self.listFeedSourceTypeSchemas(byItem: byItem, options: .init())
  }

  public func listFeedSourceTypeSchemas(
    byItem: ListFeedSourceTypeSchemasRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<FeedSourceTypeSchema, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudChronicleV1.ListFeedSourceTypeSchemasResponse
      in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listFeedSourceTypeSchemas(
    parent: Swift.String,
  ) throws -> any AsyncSequence<FeedSourceTypeSchema, Swift.Error> {
    let request = ListFeedSourceTypeSchemasRequest().with {
      $0.parent = parent
    }
    return try self.listFeedSourceTypeSchemas(byItem: request)
  }

  public func listLogTypeSchemas(request: ListLogTypeSchemasRequest) async throws
    -> GoogleCloudChronicleV1.ListLogTypeSchemasResponse
  {
    try await self.listLogTypeSchemas(request: request, options: .init())
  }

  public func listLogTypeSchemas(
    request: ListLogTypeSchemasRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.ListLogTypeSchemasResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLogTypeSchemas(
    byItem: ListLogTypeSchemasRequest
  ) throws -> any AsyncSequence<LogTypeSchema, Swift.Error> {
    try self.listLogTypeSchemas(byItem: byItem, options: .init())
  }

  public func listLogTypeSchemas(
    byItem: ListLogTypeSchemasRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<LogTypeSchema, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudChronicleV1.ListLogTypeSchemasResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listLogTypeSchemas(
    parent: Swift.String,
  ) throws -> any AsyncSequence<LogTypeSchema, Swift.Error> {
    let request = ListLogTypeSchemasRequest().with {
      $0.parent = parent
    }
    return try self.listLogTypeSchemas(byItem: request)
  }

  public func importPushLogs(request: ImportPushLogsRequest) async throws -> GoogleApi.HttpBody {
    try await self.importPushLogs(request: request, options: .init())
  }

  public func importPushLogs(
    request: ImportPushLogsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleApi.HttpBody {
    throw GoogleGax.RequestError.unimplemented
  }

  public func importPushLogs(
    parent: Swift.String,
  ) async throws -> GoogleApi.HttpBody {
    let request = ImportPushLogsRequest().with {
      $0.parent = parent
    }
    return try await self.importPushLogs(request: request)
  }

  public func generateSecret(request: GenerateSecretRequest) async throws
    -> GoogleCloudChronicleV1.GenerateSecretResponse
  {
    try await self.generateSecret(request: request, options: .init())
  }

  public func generateSecret(
    request: GenerateSecretRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.GenerateSecretResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func generateSecret(
    name: Swift.String,
  ) async throws -> GoogleCloudChronicleV1.GenerateSecretResponse {
    let request = GenerateSecretRequest().with {
      $0.name = name
    }
    return try await self.generateSecret(request: request)
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
