// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Represents a set of logic conditions used to refine various types of
/// findings such as curated rule detections.
public struct FindingsRefinement: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Full resource name for the findings refinement.
  /// Format:
  /// projects/{project}/locations/{region}/instances/{instance}/findingsRefinements/{findings_refinement}
  public var name: Swift.String = Swift.String()

  /// Display name of the findings refinement.
  public var displayName: Swift.String = Swift.String()

  /// The type of findings refinement.
  public var type: FindingsRefinementType = FindingsRefinementType()

  /// Output only. The timestamp of when the findings refinement was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The timestamp of when the findings refinement was last
  /// updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// The query for the findings refinement. Works in conjunction with the type
  /// field to determine the findings refinement behavior. The syntax of this
  /// query is the same as a UDM search string. See the following for more
  /// information:
  /// https://cloud.google.com/chronicle/docs/investigation/udm-search
  public var query: Swift.String = Swift.String()

  /// Optional. The outcome filters for the findings refinement. These allow you
  /// to specify filters that are applied to the outcome variables in the
  /// detection. All filters must be true for a detection to match the findings
  /// refinement.
  public var outcomeFilters: [OutcomeFilter] = []

  /// Initialize a new instance of `FindingsRefinement`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FindingsRefinement().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.chronicle.v1.FindingsRefinement"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
