// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleCloudGax

extension Clients {
  protocol FindingsRefinementServiceStub {
    func getFindingsRefinement(
      request: GetFindingsRefinementRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.FindingsRefinement

    func listFindingsRefinements(
      request: ListFindingsRefinementsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.ListFindingsRefinementsResponse

    func createFindingsRefinement(
      request: CreateFindingsRefinementRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.FindingsRefinement

    func updateFindingsRefinement(
      request: UpdateFindingsRefinementRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.FindingsRefinement

    func getFindingsRefinementDeployment(
      request: GetFindingsRefinementDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.FindingsRefinementDeployment

    func updateFindingsRefinementDeployment(
      request: UpdateFindingsRefinementDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.FindingsRefinementDeployment

    func listAllFindingsRefinementDeployments(
      request: ListAllFindingsRefinementDeploymentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.ListAllFindingsRefinementDeploymentsResponse

    func computeFindingsRefinementActivity(
      request: ComputeFindingsRefinementActivityRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.ComputeFindingsRefinementActivityResponse

    func computeAllFindingsRefinementActivities(
      request: ComputeAllFindingsRefinementActivitiesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.ComputeAllFindingsRefinementActivitiesResponse

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}
