// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleCloudGax

extension Clients {
  final class FindingsRefinementServiceRetry: FindingsRefinementServiceStub {
    let inner: any FindingsRefinementServiceStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any FindingsRefinementServiceStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func getFindingsRefinement(
      request: GetFindingsRefinementRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.FindingsRefinement {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetFindingsRefinementRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChronicleV1.FindingsRefinement
          in
          return try await self.inner.getFindingsRefinement(request: r, options: o)
        })
    }

    public func listFindingsRefinements(
      request: ListFindingsRefinementsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.ListFindingsRefinementsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListFindingsRefinementsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChronicleV1.ListFindingsRefinementsResponse
          in
          return try await self.inner.listFindingsRefinements(request: r, options: o)
        })
    }

    public func createFindingsRefinement(
      request: CreateFindingsRefinementRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.FindingsRefinement {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateFindingsRefinementRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChronicleV1.FindingsRefinement
          in
          return try await self.inner.createFindingsRefinement(request: r, options: o)
        })
    }

    public func updateFindingsRefinement(
      request: UpdateFindingsRefinementRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.FindingsRefinement {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateFindingsRefinementRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChronicleV1.FindingsRefinement
          in
          return try await self.inner.updateFindingsRefinement(request: r, options: o)
        })
    }

    public func getFindingsRefinementDeployment(
      request: GetFindingsRefinementDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.FindingsRefinementDeployment {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetFindingsRefinementDeploymentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChronicleV1.FindingsRefinementDeployment
          in
          return try await self.inner.getFindingsRefinementDeployment(request: r, options: o)
        })
    }

    public func updateFindingsRefinementDeployment(
      request: UpdateFindingsRefinementDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.FindingsRefinementDeployment {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateFindingsRefinementDeploymentRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudChronicleV1.FindingsRefinementDeployment
          in
          return try await self.inner.updateFindingsRefinementDeployment(request: r, options: o)
        })
    }

    public func listAllFindingsRefinementDeployments(
      request: ListAllFindingsRefinementDeploymentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.ListAllFindingsRefinementDeploymentsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListAllFindingsRefinementDeploymentsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudChronicleV1.ListAllFindingsRefinementDeploymentsResponse
          in
          return try await self.inner.listAllFindingsRefinementDeployments(request: r, options: o)
        })
    }

    public func computeFindingsRefinementActivity(
      request: ComputeFindingsRefinementActivityRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.ComputeFindingsRefinementActivityResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ComputeFindingsRefinementActivityRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudChronicleV1.ComputeFindingsRefinementActivityResponse
          in
          return try await self.inner.computeFindingsRefinementActivity(request: r, options: o)
        })
    }

    public func computeAllFindingsRefinementActivities(
      request: ComputeAllFindingsRefinementActivitiesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.ComputeAllFindingsRefinementActivitiesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ComputeAllFindingsRefinementActivitiesRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudChronicleV1.ComputeAllFindingsRefinementActivitiesResponse
          in
          return try await self.inner.computeAllFindingsRefinementActivities(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
