// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The FindingsRefinementDeployment resource represents the deployment state of
/// a findings refinement.
public struct FindingsRefinementDeployment: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the findings refinement deployment.
  /// Format:
  /// projects/{project}/locations/{location}/instances/{instance}/findingsRefinements/{findings_refinement}/deployment
  public var name: Swift.String = Swift.String()

  /// Whether the findings refinement is currently deployed continuously against
  /// incoming findings.
  public var enabled: Swift.Bool = Swift.Bool()

  /// The archive state of the findings refinement deployment.
  /// Cannot be set to true unless enabled is set to false.
  /// If currently set to true, enabled cannot be updated to true.
  public var archived: Swift.Bool = Swift.Bool()

  /// Output only. The timestamp when the findings refinement deployment was last
  /// updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// The resources which the findings refinement is applied to. Corresponds to
  /// the type of the findings refinement.
  public var findingsRefinementApplication: OneOf_FindingsRefinementApplication? = nil

  /// Initialize a new instance of `FindingsRefinementDeployment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FindingsRefinementDeployment().with { $0.detectionExclusionApplication = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case detectionExclusionApplication = "detectionExclusionApplication"
    case name = "name"
    case enabled = "enabled"
    case archived = "archived"
    case updateTime = "updateTime"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.enabled = try container.decode(Swift.Bool.self, forKey: .enabled)
    self.archived = try container.decode(Swift.Bool.self, forKey: .archived)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .updateTime)

    var findingsRefinementApplication: OneOf_FindingsRefinementApplication? = nil
    let findingsRefinementApplicationCheckAndSet = {
      if findingsRefinementApplication != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'findingsRefinementApplication'"))
      }
      findingsRefinementApplication = $0
    }
    if let detectionExclusionApplication = try container.decodeIfPresent(
      DetectionExclusionApplication?.self, forKey: .detectionExclusionApplication)
    {
      try findingsRefinementApplicationCheckAndSet(
        .detectionExclusionApplication(detectionExclusionApplication))
    }
    self.findingsRefinementApplication = findingsRefinementApplication
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.enabled, forKey: .enabled)
    try container.encode(self.archived, forKey: .archived)
    try container.encode(self.updateTime, forKey: .updateTime)

    if let choice = self.findingsRefinementApplication {
      switch choice {
      case .detectionExclusionApplication(let value):
        try container.encode(value, forKey: .detectionExclusionApplication)
      }
    }
  }

  /// The resources which the findings refinement is applied to. Corresponds to
  /// the type of the findings refinement.
  public enum OneOf_FindingsRefinementApplication: Codable, Equatable, Sendable {
    /// The resources which the detection exclusion is applied to.
    indirect case detectionExclusionApplication(DetectionExclusionApplication?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.chronicle.v1.FindingsRefinementDeployment"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
