// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Google Cloud Storage settings.
public struct GoogleCloudStorageSettings: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Bucket URI.
  public var bucketUri: Swift.String = Swift.String()

  /// The URI source type.
  public var sourceType: URISourceType = URISourceType()

  /// Source deletion option.
  public var sourceDeletionOption: SourceDeletionOption = SourceDeletionOption()

  /// Output only. Service Account Chronicle will be using to pull data.
  public var chronicleServiceAccount: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `GoogleCloudStorageSettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GoogleCloudStorageSettings().with { $0.bucketUri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let bucketUri = CodingKeys(stringValue: "bucketUri")
    static let sourceType = CodingKeys(stringValue: "sourceType")
    static let sourceDeletionOption = CodingKeys(stringValue: "sourceDeletionOption")
    static let chronicleServiceAccount = CodingKeys(stringValue: "chronicleServiceAccount")

    static let _knownKeys: Set<Swift.String> = [
      "bucketUri",
      "sourceType",
      "sourceDeletionOption",
      "chronicleServiceAccount",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .bucketUri) {
      self.bucketUri = value
    }
    if let value = try container.decodeIfPresent(URISourceType.self, forKey: .sourceType) {
      self.sourceType = value
    }
    if let value = try container.decodeIfPresent(
      SourceDeletionOption.self, forKey: .sourceDeletionOption)
    {
      self.sourceDeletionOption = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .chronicleServiceAccount)
    {
      self.chronicleServiceAccount = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.bucketUri, forKey: .bucketUri)
    try container.encode(self.sourceType, forKey: .sourceType)
    try container.encode(self.sourceDeletionOption, forKey: .sourceDeletionOption)
    try container.encode(self.chronicleServiceAccount, forKey: .chronicleServiceAccount)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.chronicle.v1.GoogleCloudStorageSettings"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
