// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message to list FeaturedContentNativeDashboards.
public struct ListFeaturedContentNativeDashboardsRequest: Codable, Equatable, GoogleCloudWKT
    ._AnyPackable,
  Sendable
{
  /// Required. The parent, which owns this collection of
  /// FeaturedContentNativeDashboards. Format:
  /// projects/{project}/locations/{location}/instances/{instance}/contentHub
  public var parent: Swift.String = Swift.String()

  /// Optional. The maximum number of FeaturedContentNativeDashboards to return.
  /// The service may return fewer than this value. If unspecified, at most 100
  /// FeaturedContentNativeDashboards will be returned. The maximum value is 100;
  /// values above 100 will be coerced to 100.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A page token, received from a previous
  /// `ListFeaturedContentNativeDashboards` call. Provide this to retrieve the
  /// subsequent page.
  ///
  /// When paginating, all other parameters provided to
  /// `ListFeaturedContentNativeDashboards` must match the call that provided the
  /// page token.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. The filter to apply to list the FeaturedContentNativeDashboards.
  ///
  /// The filter syntax follows Google Cloud syntax: https://google.aip.dev/160.
  ///
  /// Supported fields for filtering:
  ///
  /// *   `name`: The resource name of the featured content.
  /// *   `content_metadata.description`: The description of the featured
  /// content.
  ///
  /// When a literal value is provided without a field, it will perform a
  /// substring search across both `name` and `content_metadata.description`.
  ///
  /// Examples:
  ///
  /// *   `"test"`: Matches featured content where either the name or description
  ///     contains "test" as a substring.
  /// *   `name="test"`: Matches featured content where the name contains "test".
  /// *   `content_metadata.description="test"`: Matches featured content where
  ///     the description contains "test".
  public var filter: Swift.String = Swift.String()

  /// Initialize a new instance of `ListFeaturedContentNativeDashboardsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListFeaturedContentNativeDashboardsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.chronicle.v1.ListFeaturedContentNativeDashboardsRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
