// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleCloudGax

/// A service providing functionality for managing native dashboards.
///
/// @Snippet(path: "NativeDashboardServiceQuickstart")
public final class NativeDashboardServiceClient: Clients.NativeDashboardServiceProtocol, Sendable {
  let inner: any Clients.NativeDashboardServiceStub

  /// Creates a new `NativeDashboardServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.NativeDashboardServiceStub = try Clients.NativeDashboardServiceTransport(
      options)
    inner = Clients.NativeDashboardServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.NativeDashboardServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Create a dashboard.
  ///
  /// @Snippet(path: "NativeDashboardService_CreateNativeDashboard")
  public func createNativeDashboard(
    request: CreateNativeDashboardRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.NativeDashboard {
    try await self.inner.createNativeDashboard(request: request, options: options)
  }

  /// Get a dashboard.
  ///
  /// @Snippet(path: "NativeDashboardService_GetNativeDashboard")
  public func getNativeDashboard(
    request: GetNativeDashboardRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.NativeDashboard {
    try await self.inner.getNativeDashboard(request: request, options: options)
  }

  /// List all dashboards.
  ///
  /// @Snippet(path: "NativeDashboardService_ListNativeDashboards")
  public func listNativeDashboards(
    request: ListNativeDashboardsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.ListNativeDashboardsResponse {
    try await self.inner.listNativeDashboards(request: request, options: options)
  }

  /// List all dashboards.
  ///
  /// @Snippet(path: "NativeDashboardService_ListNativeDashboards")
  public func listNativeDashboards(
    byItem: ListNativeDashboardsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<NativeDashboard, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudChronicleV1.ListNativeDashboardsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listNativeDashboards(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Update a dashboard.
  ///
  /// @Snippet(path: "NativeDashboardService_UpdateNativeDashboard")
  public func updateNativeDashboard(
    request: UpdateNativeDashboardRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.NativeDashboard {
    try await self.inner.updateNativeDashboard(request: request, options: options)
  }

  /// Duplicate a dashboard.
  ///
  /// @Snippet(path: "NativeDashboardService_DuplicateNativeDashboard")
  public func duplicateNativeDashboard(
    request: DuplicateNativeDashboardRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.NativeDashboard {
    try await self.inner.duplicateNativeDashboard(request: request, options: options)
  }

  /// Delete a dashboard.
  ///
  /// @Snippet(path: "NativeDashboardService_DeleteNativeDashboard")
  public func deleteNativeDashboard(
    request: DeleteNativeDashboardRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteNativeDashboard(request: request, options: options)
  }

  /// Add chart in a dashboard.
  ///
  /// @Snippet(path: "NativeDashboardService_AddChart")
  public func addChart(
    request: AddChartRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.AddChartResponse {
    try await self.inner.addChart(request: request, options: options)
  }

  /// Remove chart from a dashboard.
  ///
  /// @Snippet(path: "NativeDashboardService_RemoveChart")
  public func removeChart(
    request: RemoveChartRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.NativeDashboard {
    try await self.inner.removeChart(request: request, options: options)
  }

  /// Edit chart in a dashboard.
  ///
  /// @Snippet(path: "NativeDashboardService_EditChart")
  public func editChart(
    request: EditChartRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.EditChartResponse {
    try await self.inner.editChart(request: request, options: options)
  }

  /// Duplicate chart in a dashboard.
  ///
  /// @Snippet(path: "NativeDashboardService_DuplicateChart")
  public func duplicateChart(
    request: DuplicateChartRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.DuplicateChartResponse {
    try await self.inner.duplicateChart(request: request, options: options)
  }

  /// Exports the dashboards.
  ///
  /// @Snippet(path: "NativeDashboardService_ExportNativeDashboards")
  public func exportNativeDashboards(
    request: ExportNativeDashboardsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.ExportNativeDashboardsResponse {
    try await self.inner.exportNativeDashboards(request: request, options: options)
  }

  /// Imports the dashboards.
  ///
  /// @Snippet(path: "NativeDashboardService_ImportNativeDashboards")
  public func importNativeDashboards(
    request: ImportNativeDashboardsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.ImportNativeDashboardsResponse {
    try await self.inner.importNativeDashboards(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "NativeDashboardService_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "NativeDashboardService_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "NativeDashboardService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "NativeDashboardService_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "NativeDashboardService_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `NativeDashboardServiceClient`.
  ///
  /// To mock `NativeDashboardServiceClient` change your functions to receive
  /// `some NativeDashboardServiceProtocol` or `any NativeDashboardServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol NativeDashboardServiceProtocol {
    /// See `NativeDashboardServiceClient.createNativeDashboard`.
    func createNativeDashboard(request: CreateNativeDashboardRequest) async throws
      -> GoogleCloudChronicleV1.NativeDashboard

    /// See `NativeDashboardServiceClient.createNativeDashboard`.
    func createNativeDashboard(
      parent: Swift.String,
      nativeDashboard: NativeDashboard?,
    ) async throws -> GoogleCloudChronicleV1.NativeDashboard

    /// See `NativeDashboardServiceClient.getNativeDashboard`.
    func getNativeDashboard(request: GetNativeDashboardRequest) async throws
      -> GoogleCloudChronicleV1.NativeDashboard

    /// See `NativeDashboardServiceClient.getNativeDashboard`.
    func getNativeDashboard(
      name: Swift.String,
    ) async throws -> GoogleCloudChronicleV1.NativeDashboard

    /// See `NativeDashboardServiceClient.listNativeDashboards`.
    func listNativeDashboards(request: ListNativeDashboardsRequest) async throws
      -> GoogleCloudChronicleV1.ListNativeDashboardsResponse

    /// See `NativeDashboardServiceClient.listNativeDashboards`.
    func listNativeDashboards(
      byItem: ListNativeDashboardsRequest
    ) throws -> any AsyncSequence<NativeDashboard, Swift.Error>

    /// See `NativeDashboardServiceClient.listNativeDashboards`.
    func listNativeDashboards(
      parent: Swift.String,
    ) throws -> any AsyncSequence<NativeDashboard, Swift.Error>

    /// See `NativeDashboardServiceClient.updateNativeDashboard`.
    func updateNativeDashboard(request: UpdateNativeDashboardRequest) async throws
      -> GoogleCloudChronicleV1.NativeDashboard

    /// See `NativeDashboardServiceClient.updateNativeDashboard`.
    func updateNativeDashboard(
      nativeDashboard: NativeDashboard?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> GoogleCloudChronicleV1.NativeDashboard

    /// See `NativeDashboardServiceClient.duplicateNativeDashboard`.
    func duplicateNativeDashboard(request: DuplicateNativeDashboardRequest) async throws
      -> GoogleCloudChronicleV1.NativeDashboard

    /// See `NativeDashboardServiceClient.duplicateNativeDashboard`.
    func duplicateNativeDashboard(
      name: Swift.String,
      nativeDashboard: NativeDashboard?,
    ) async throws -> GoogleCloudChronicleV1.NativeDashboard

    /// See `NativeDashboardServiceClient.deleteNativeDashboard`.
    func deleteNativeDashboard(request: DeleteNativeDashboardRequest) async throws

    /// See `NativeDashboardServiceClient.deleteNativeDashboard`.
    func deleteNativeDashboard(
      name: Swift.String,
    ) async throws

    /// See `NativeDashboardServiceClient.addChart`.
    func addChart(request: AddChartRequest) async throws -> GoogleCloudChronicleV1.AddChartResponse

    /// See `NativeDashboardServiceClient.addChart`.
    func addChart(
      name: Swift.String,
      dashboardQuery: DashboardQuery?,
      dashboardChart: DashboardChart?,
    ) async throws -> GoogleCloudChronicleV1.AddChartResponse

    /// See `NativeDashboardServiceClient.removeChart`.
    func removeChart(request: RemoveChartRequest) async throws
      -> GoogleCloudChronicleV1.NativeDashboard

    /// See `NativeDashboardServiceClient.removeChart`.
    func removeChart(
      name: Swift.String,
    ) async throws -> GoogleCloudChronicleV1.NativeDashboard

    /// See `NativeDashboardServiceClient.editChart`.
    func editChart(request: EditChartRequest) async throws
      -> GoogleCloudChronicleV1.EditChartResponse

    /// See `NativeDashboardServiceClient.editChart`.
    func editChart(
      name: Swift.String,
      dashboardQuery: DashboardQuery?,
      dashboardChart: DashboardChart?,
      editMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> GoogleCloudChronicleV1.EditChartResponse

    /// See `NativeDashboardServiceClient.duplicateChart`.
    func duplicateChart(request: DuplicateChartRequest) async throws
      -> GoogleCloudChronicleV1.DuplicateChartResponse

    /// See `NativeDashboardServiceClient.duplicateChart`.
    func duplicateChart(
      name: Swift.String,
    ) async throws -> GoogleCloudChronicleV1.DuplicateChartResponse

    /// See `NativeDashboardServiceClient.exportNativeDashboards`.
    func exportNativeDashboards(request: ExportNativeDashboardsRequest) async throws
      -> GoogleCloudChronicleV1.ExportNativeDashboardsResponse

    /// See `NativeDashboardServiceClient.exportNativeDashboards`.
    func exportNativeDashboards(
      parent: Swift.String,
      names: [Swift.String],
    ) async throws -> GoogleCloudChronicleV1.ExportNativeDashboardsResponse

    /// See `NativeDashboardServiceClient.importNativeDashboards`.
    func importNativeDashboards(request: ImportNativeDashboardsRequest) async throws
      -> GoogleCloudChronicleV1.ImportNativeDashboardsResponse

    /// See `NativeDashboardServiceClient.importNativeDashboards`.
    func importNativeDashboards(
      parent: Swift.String,
      source: ImportNativeDashboardsInlineSource?,
    ) async throws -> GoogleCloudChronicleV1.ImportNativeDashboardsResponse

    /// See `NativeDashboardServiceClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `NativeDashboardServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `NativeDashboardServiceClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `NativeDashboardServiceClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `NativeDashboardServiceClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `NativeDashboardServiceClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `NativeDashboardServiceClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `NativeDashboardServiceClient.createNativeDashboard`.
    func createNativeDashboard(
      request: CreateNativeDashboardRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.NativeDashboard

    /// See `NativeDashboardServiceClient.getNativeDashboard`.
    func getNativeDashboard(
      request: GetNativeDashboardRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.NativeDashboard

    /// See `NativeDashboardServiceClient.listNativeDashboards`.
    func listNativeDashboards(
      request: ListNativeDashboardsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.ListNativeDashboardsResponse

    /// See `NativeDashboardServiceClient.listNativeDashboards`.
    func listNativeDashboards(
      byItem: ListNativeDashboardsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<NativeDashboard, Swift.Error>

    /// See `NativeDashboardServiceClient.updateNativeDashboard`.
    func updateNativeDashboard(
      request: UpdateNativeDashboardRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.NativeDashboard

    /// See `NativeDashboardServiceClient.duplicateNativeDashboard`.
    func duplicateNativeDashboard(
      request: DuplicateNativeDashboardRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.NativeDashboard

    /// See `NativeDashboardServiceClient.deleteNativeDashboard`.
    func deleteNativeDashboard(
      request: DeleteNativeDashboardRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `NativeDashboardServiceClient.addChart`.
    func addChart(
      request: AddChartRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.AddChartResponse

    /// See `NativeDashboardServiceClient.removeChart`.
    func removeChart(
      request: RemoveChartRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.NativeDashboard

    /// See `NativeDashboardServiceClient.editChart`.
    func editChart(
      request: EditChartRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.EditChartResponse

    /// See `NativeDashboardServiceClient.duplicateChart`.
    func duplicateChart(
      request: DuplicateChartRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.DuplicateChartResponse

    /// See `NativeDashboardServiceClient.exportNativeDashboards`.
    func exportNativeDashboards(
      request: ExportNativeDashboardsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.ExportNativeDashboardsResponse

    /// See `NativeDashboardServiceClient.importNativeDashboards`.
    func importNativeDashboards(
      request: ImportNativeDashboardsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.ImportNativeDashboardsResponse

    /// See `NativeDashboardServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `NativeDashboardServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `NativeDashboardServiceClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `NativeDashboardServiceClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.NativeDashboardServiceProtocol {
  public func createNativeDashboard(request: CreateNativeDashboardRequest) async throws
    -> GoogleCloudChronicleV1.NativeDashboard
  {
    try await self.createNativeDashboard(request: request, options: .init())
  }

  public func createNativeDashboard(
    request: CreateNativeDashboardRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.NativeDashboard {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createNativeDashboard(
    parent: Swift.String,
    nativeDashboard: NativeDashboard?,
  ) async throws -> GoogleCloudChronicleV1.NativeDashboard {
    let request = CreateNativeDashboardRequest().with {
      $0.parent = parent
      $0.nativeDashboard = nativeDashboard
    }
    return try await self.createNativeDashboard(request: request)
  }

  public func getNativeDashboard(request: GetNativeDashboardRequest) async throws
    -> GoogleCloudChronicleV1.NativeDashboard
  {
    try await self.getNativeDashboard(request: request, options: .init())
  }

  public func getNativeDashboard(
    request: GetNativeDashboardRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.NativeDashboard {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getNativeDashboard(
    name: Swift.String,
  ) async throws -> GoogleCloudChronicleV1.NativeDashboard {
    let request = GetNativeDashboardRequest().with {
      $0.name = name
    }
    return try await self.getNativeDashboard(request: request)
  }

  public func listNativeDashboards(request: ListNativeDashboardsRequest) async throws
    -> GoogleCloudChronicleV1.ListNativeDashboardsResponse
  {
    try await self.listNativeDashboards(request: request, options: .init())
  }

  public func listNativeDashboards(
    request: ListNativeDashboardsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.ListNativeDashboardsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listNativeDashboards(
    byItem: ListNativeDashboardsRequest
  ) throws -> any AsyncSequence<NativeDashboard, Swift.Error> {
    try self.listNativeDashboards(byItem: byItem, options: .init())
  }

  public func listNativeDashboards(
    byItem: ListNativeDashboardsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<NativeDashboard, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudChronicleV1.ListNativeDashboardsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listNativeDashboards(
    parent: Swift.String,
  ) throws -> any AsyncSequence<NativeDashboard, Swift.Error> {
    let request = ListNativeDashboardsRequest().with {
      $0.parent = parent
    }
    return try self.listNativeDashboards(byItem: request)
  }

  public func updateNativeDashboard(request: UpdateNativeDashboardRequest) async throws
    -> GoogleCloudChronicleV1.NativeDashboard
  {
    try await self.updateNativeDashboard(request: request, options: .init())
  }

  public func updateNativeDashboard(
    request: UpdateNativeDashboardRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.NativeDashboard {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateNativeDashboard(
    nativeDashboard: NativeDashboard?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> GoogleCloudChronicleV1.NativeDashboard {
    let request = UpdateNativeDashboardRequest().with {
      $0.nativeDashboard = nativeDashboard
      $0.updateMask = updateMask
    }
    return try await self.updateNativeDashboard(request: request)
  }

  public func duplicateNativeDashboard(request: DuplicateNativeDashboardRequest) async throws
    -> GoogleCloudChronicleV1.NativeDashboard
  {
    try await self.duplicateNativeDashboard(request: request, options: .init())
  }

  public func duplicateNativeDashboard(
    request: DuplicateNativeDashboardRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.NativeDashboard {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func duplicateNativeDashboard(
    name: Swift.String,
    nativeDashboard: NativeDashboard?,
  ) async throws -> GoogleCloudChronicleV1.NativeDashboard {
    let request = DuplicateNativeDashboardRequest().with {
      $0.name = name
      $0.nativeDashboard = nativeDashboard
    }
    return try await self.duplicateNativeDashboard(request: request)
  }

  public func deleteNativeDashboard(request: DeleteNativeDashboardRequest) async throws {
    try await self.deleteNativeDashboard(request: request, options: .init())
  }

  public func deleteNativeDashboard(
    request: DeleteNativeDashboardRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteNativeDashboard(
    name: Swift.String,
  ) async throws {
    let request = DeleteNativeDashboardRequest().with {
      $0.name = name
    }
    try await self.deleteNativeDashboard(request: request)
  }

  public func addChart(request: AddChartRequest) async throws
    -> GoogleCloudChronicleV1.AddChartResponse
  {
    try await self.addChart(request: request, options: .init())
  }

  public func addChart(
    request: AddChartRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.AddChartResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func addChart(
    name: Swift.String,
    dashboardQuery: DashboardQuery?,
    dashboardChart: DashboardChart?,
  ) async throws -> GoogleCloudChronicleV1.AddChartResponse {
    let request = AddChartRequest().with {
      $0.name = name
      $0.dashboardQuery = dashboardQuery
      $0.dashboardChart = dashboardChart
    }
    return try await self.addChart(request: request)
  }

  public func removeChart(request: RemoveChartRequest) async throws
    -> GoogleCloudChronicleV1.NativeDashboard
  {
    try await self.removeChart(request: request, options: .init())
  }

  public func removeChart(
    request: RemoveChartRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.NativeDashboard {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func removeChart(
    name: Swift.String,
  ) async throws -> GoogleCloudChronicleV1.NativeDashboard {
    let request = RemoveChartRequest().with {
      $0.name = name
    }
    return try await self.removeChart(request: request)
  }

  public func editChart(request: EditChartRequest) async throws
    -> GoogleCloudChronicleV1.EditChartResponse
  {
    try await self.editChart(request: request, options: .init())
  }

  public func editChart(
    request: EditChartRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.EditChartResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func editChart(
    name: Swift.String,
    dashboardQuery: DashboardQuery?,
    dashboardChart: DashboardChart?,
    editMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> GoogleCloudChronicleV1.EditChartResponse {
    let request = EditChartRequest().with {
      $0.name = name
      $0.dashboardQuery = dashboardQuery
      $0.dashboardChart = dashboardChart
      $0.editMask = editMask
    }
    return try await self.editChart(request: request)
  }

  public func duplicateChart(request: DuplicateChartRequest) async throws
    -> GoogleCloudChronicleV1.DuplicateChartResponse
  {
    try await self.duplicateChart(request: request, options: .init())
  }

  public func duplicateChart(
    request: DuplicateChartRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.DuplicateChartResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func duplicateChart(
    name: Swift.String,
  ) async throws -> GoogleCloudChronicleV1.DuplicateChartResponse {
    let request = DuplicateChartRequest().with {
      $0.name = name
    }
    return try await self.duplicateChart(request: request)
  }

  public func exportNativeDashboards(request: ExportNativeDashboardsRequest) async throws
    -> GoogleCloudChronicleV1.ExportNativeDashboardsResponse
  {
    try await self.exportNativeDashboards(request: request, options: .init())
  }

  public func exportNativeDashboards(
    request: ExportNativeDashboardsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.ExportNativeDashboardsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func exportNativeDashboards(
    parent: Swift.String,
    names: [Swift.String],
  ) async throws -> GoogleCloudChronicleV1.ExportNativeDashboardsResponse {
    let request = ExportNativeDashboardsRequest().with {
      $0.parent = parent
      $0.names = names
    }
    return try await self.exportNativeDashboards(request: request)
  }

  public func importNativeDashboards(request: ImportNativeDashboardsRequest) async throws
    -> GoogleCloudChronicleV1.ImportNativeDashboardsResponse
  {
    try await self.importNativeDashboards(request: request, options: .init())
  }

  public func importNativeDashboards(
    request: ImportNativeDashboardsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.ImportNativeDashboardsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func importNativeDashboards(
    parent: Swift.String,
    source: ImportNativeDashboardsInlineSource?,
  ) async throws -> GoogleCloudChronicleV1.ImportNativeDashboardsResponse {
    let request = ImportNativeDashboardsRequest().with {
      $0.parent = parent
      $0.source = source
    }
    return try await self.importNativeDashboards(request: request)
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
