// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// OAuth 2.0 JWT grant. See, https://tools.ietf.org/html/rfc7519
public struct OAuthJWTCredentials: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Token endpoint to get the OAuth token from.
  public var tokenEndpoint: Swift.String = Swift.String()

  /// Claims.
  public var claims: Claims? = nil

  /// Credentials.
  public var credentials: OneOf_Credentials? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `OAuthJWTCredentials`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OAuthJWTCredentials().with { $0.rsCredentials = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let rsCredentials = CodingKeys(stringValue: "rsCredentials")
    static let tokenEndpoint = CodingKeys(stringValue: "tokenEndpoint")
    static let claims = CodingKeys(stringValue: "claims")

    static let _knownKeys: Set<Swift.String> = [
      "rsCredentials",
      "tokenEndpoint",
      "claims",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .tokenEndpoint) {
      self.tokenEndpoint = value
    }
    self.claims = try container.decodeIfPresent(Claims.self, forKey: .claims)

    var credentials: OneOf_Credentials? = nil
    let credentialsCheckAndSet = {
      if credentials != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'credentials'"))
      }
      credentials = $0
    }
    if let rsCredentials = try container.decodeIfPresent(
      RSCredentials?.self, forKey: .rsCredentials)
    {
      try credentialsCheckAndSet(.rsCredentials(rsCredentials))
    }
    self.credentials = credentials
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.tokenEndpoint, forKey: .tokenEndpoint)
    try container.encodeIfPresent(self.claims, forKey: .claims)

    if let choice = self.credentials {
      switch choice {
      case .rsCredentials(let value):
        try container.encode(value, forKey: .rsCredentials)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Credentials.
  public enum OneOf_Credentials: Codable, Equatable, Sendable {
    /// RS credentials.
    indirect case rsCredentials(RSCredentials?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.chronicle.v1.OAuthJWTCredentials"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
