// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleCloudGax

/// RuleExecutionErrorService contains endpoints related to rule execution
/// errors.
///
/// @Snippet(path: "RuleExecutionErrorServiceQuickstart")
public final class RuleExecutionErrorServiceClient: Clients.RuleExecutionErrorServiceProtocol,
  Sendable
{
  let inner: any Clients.RuleExecutionErrorServiceStub

  /// Creates a new `RuleExecutionErrorServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.RuleExecutionErrorServiceStub =
      try Clients.RuleExecutionErrorServiceTransport(options)
    inner = Clients.RuleExecutionErrorServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.RuleExecutionErrorServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Lists rule execution errors.
  ///
  /// @Snippet(path: "RuleExecutionErrorService_ListRuleExecutionErrors")
  public func listRuleExecutionErrors(
    request: ListRuleExecutionErrorsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.ListRuleExecutionErrorsResponse {
    try await self.inner.listRuleExecutionErrors(request: request, options: options)
  }

  /// Lists rule execution errors.
  ///
  /// @Snippet(path: "RuleExecutionErrorService_ListRuleExecutionErrors")
  public func listRuleExecutionErrors(
    byItem: ListRuleExecutionErrorsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<RuleExecutionError, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudChronicleV1.ListRuleExecutionErrorsResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listRuleExecutionErrors(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "RuleExecutionErrorService_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "RuleExecutionErrorService_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "RuleExecutionErrorService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "RuleExecutionErrorService_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "RuleExecutionErrorService_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `RuleExecutionErrorServiceClient`.
  ///
  /// To mock `RuleExecutionErrorServiceClient` change your functions to receive
  /// `some RuleExecutionErrorServiceProtocol` or `any RuleExecutionErrorServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol RuleExecutionErrorServiceProtocol {
    /// See `RuleExecutionErrorServiceClient.listRuleExecutionErrors`.
    func listRuleExecutionErrors(request: ListRuleExecutionErrorsRequest) async throws
      -> GoogleCloudChronicleV1.ListRuleExecutionErrorsResponse

    /// See `RuleExecutionErrorServiceClient.listRuleExecutionErrors`.
    func listRuleExecutionErrors(
      byItem: ListRuleExecutionErrorsRequest
    ) throws -> any AsyncSequence<RuleExecutionError, Swift.Error>

    /// See `RuleExecutionErrorServiceClient.listRuleExecutionErrors`.
    func listRuleExecutionErrors(
      parent: Swift.String,
    ) throws -> any AsyncSequence<RuleExecutionError, Swift.Error>

    /// See `RuleExecutionErrorServiceClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `RuleExecutionErrorServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `RuleExecutionErrorServiceClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `RuleExecutionErrorServiceClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `RuleExecutionErrorServiceClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `RuleExecutionErrorServiceClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `RuleExecutionErrorServiceClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `RuleExecutionErrorServiceClient.listRuleExecutionErrors`.
    func listRuleExecutionErrors(
      request: ListRuleExecutionErrorsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChronicleV1.ListRuleExecutionErrorsResponse

    /// See `RuleExecutionErrorServiceClient.listRuleExecutionErrors`.
    func listRuleExecutionErrors(
      byItem: ListRuleExecutionErrorsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<RuleExecutionError, Swift.Error>

    /// See `RuleExecutionErrorServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `RuleExecutionErrorServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `RuleExecutionErrorServiceClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `RuleExecutionErrorServiceClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.RuleExecutionErrorServiceProtocol {
  public func listRuleExecutionErrors(request: ListRuleExecutionErrorsRequest) async throws
    -> GoogleCloudChronicleV1.ListRuleExecutionErrorsResponse
  {
    try await self.listRuleExecutionErrors(request: request, options: .init())
  }

  public func listRuleExecutionErrors(
    request: ListRuleExecutionErrorsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudChronicleV1.ListRuleExecutionErrorsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listRuleExecutionErrors(
    byItem: ListRuleExecutionErrorsRequest
  ) throws -> any AsyncSequence<RuleExecutionError, Swift.Error> {
    try self.listRuleExecutionErrors(byItem: byItem, options: .init())
  }

  public func listRuleExecutionErrors(
    byItem: ListRuleExecutionErrorsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<RuleExecutionError, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudChronicleV1.ListRuleExecutionErrorsResponse
      in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listRuleExecutionErrors(
    parent: Swift.String,
  ) throws -> any AsyncSequence<RuleExecutionError, Swift.Error> {
    let request = ListRuleExecutionErrorsRequest().with {
      $0.parent = parent
    }
    return try self.listRuleExecutionErrors(byItem: request)
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
