// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Amazon S3 auth.
public struct S3Auth: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Access key ID. Used when using access key auth.
  public var accessKeyId: Swift.String = Swift.String()

  /// Secret access key. Used when using access key auth.
  public var secretAccessKey: Swift.String = Swift.String()

  /// Client ID. Used when using OAuth auth.
  public var clientId: Swift.String = Swift.String()

  /// Client secret. Used when using OAuth auth.
  public var clientSecret: Swift.String = Swift.String()

  /// Refresh URI. Used when using OAuth auth.
  public var refreshUri: Swift.String = Swift.String()

  /// S3 Region.
  public var region: S3Region = S3Region()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `S3Auth`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = S3Auth().with { $0.accessKeyId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let accessKeyId = CodingKeys(stringValue: "accessKeyId")
    static let secretAccessKey = CodingKeys(stringValue: "secretAccessKey")
    static let clientId = CodingKeys(stringValue: "clientId")
    static let clientSecret = CodingKeys(stringValue: "clientSecret")
    static let refreshUri = CodingKeys(stringValue: "refreshUri")
    static let region = CodingKeys(stringValue: "region")

    static let _knownKeys: Set<Swift.String> = [
      "accessKeyId",
      "secretAccessKey",
      "clientId",
      "clientSecret",
      "refreshUri",
      "region",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .accessKeyId) {
      self.accessKeyId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .secretAccessKey) {
      self.secretAccessKey = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .clientId) {
      self.clientId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .clientSecret) {
      self.clientSecret = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .refreshUri) {
      self.refreshUri = value
    }
    if let value = try container.decodeIfPresent(S3Region.self, forKey: .region) {
      self.region = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.accessKeyId, forKey: .accessKeyId)
    try container.encode(self.secretAccessKey, forKey: .secretAccessKey)
    try container.encode(self.clientId, forKey: .clientId)
    try container.encode(self.clientSecret, forKey: .clientSecret)
    try container.encode(self.refreshUri, forKey: .refreshUri)
    try container.encode(self.region, forKey: .region)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.chronicle.v1.S3Auth"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
