// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// An SSL client certificate keypair.
public struct SSLClientKeypair: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The encoded private key. The string should be a private key in PEM format,
  /// and should include the begin header and end footer lines. It may also
  /// include newlines.
  ///
  /// Example:
  /// -----BEGIN RSA PRIVATE KEY-----
  /// Proc-Type: 4,ENCRYPTED
  /// DEK-Info: DES-EDE3-CBC,F23074E02CF47304
  ///
  /// <REDACTED>
  /// -----END RSA PRIVATE KEY-----
  public var encodedPrivateKey: Swift.String = Swift.String()

  /// The encoded SSL certificate. The string should be an SSL certificate in
  /// PEM format, and should include the begin header and end footer lines. It
  /// may also include newlines.
  ///
  /// Example:
  /// -----BEGIN CERTIFICATE-----
  /// <REDACTED>
  /// -----END CERTIFICATE-----
  public var sslCertificate: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SSLClientKeypair`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SSLClientKeypair().with { $0.encodedPrivateKey = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let encodedPrivateKey = CodingKeys(stringValue: "encodedPrivateKey")
    static let sslCertificate = CodingKeys(stringValue: "sslCertificate")

    static let _knownKeys: Set<Swift.String> = [
      "encodedPrivateKey",
      "sslCertificate",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .encodedPrivateKey) {
      self.encodedPrivateKey = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sslCertificate) {
      self.sslCertificate = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.encodedPrivateKey, forKey: .encodedPrivateKey)
    try container.encode(self.sslCertificate, forKey: .sslCertificate)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.chronicle.v1.SSLClientKeypair"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
