// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// ThreatConnectIoCV3Settings
public struct ThreatConnectIoCV3Settings: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Input only. UsernameSecretAuth.
  public var authentication: UsernameSecretAuth? = nil

  /// Required. hostname.
  public var hostname: Swift.String = Swift.String()

  /// Required. Owners.
  public var owners: [Swift.String] = []

  /// Optional. ThreatConnect Query Language filter.
  public var tqlQuery: Swift.String = Swift.String()

  /// Optional. Fields
  public var fields: [Swift.String] = []

  /// Optional. Schedule
  public var schedule: Swift.Int32 = Swift.Int32()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ThreatConnectIoCV3Settings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ThreatConnectIoCV3Settings().with { $0.authentication = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let authentication = CodingKeys(stringValue: "authentication")
    static let hostname = CodingKeys(stringValue: "hostname")
    static let owners = CodingKeys(stringValue: "owners")
    static let tqlQuery = CodingKeys(stringValue: "tqlQuery")
    static let fields = CodingKeys(stringValue: "fields")
    static let schedule = CodingKeys(stringValue: "schedule")

    static let _knownKeys: Set<Swift.String> = [
      "authentication",
      "hostname",
      "owners",
      "tqlQuery",
      "fields",
      "schedule",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.authentication = try container.decodeIfPresent(
      UsernameSecretAuth.self, forKey: .authentication)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .hostname) {
      self.hostname = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .owners) {
      self.owners = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .tqlQuery) {
      self.tqlQuery = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .fields) {
      self.fields = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .schedule) {
      self.schedule = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.authentication, forKey: .authentication)
    try container.encode(self.hostname, forKey: .hostname)
    try container.encode(self.owners, forKey: .owners)
    try container.encode(self.tqlQuery, forKey: .tqlQuery)
    try container.encode(self.fields, forKey: .fields)
    try container.encode(self.schedule, forKey: .schedule)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.chronicle.v1.ThreatConnectIoCV3Settings"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
