// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A watchlist is a list of entities that allows for bulk operations over the
/// included entities.
public struct Watchlist: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. Resource name of the watchlist.
  /// Format:
  /// `projects/{project}/locations/{location}/instances/{instance}/watchlists/{watchlist}`
  public var name: Swift.String = Swift.String()

  /// Required. Display name of the watchlist.
  /// Note that it must be at least one character and less than 63 characters
  /// (https://google.aip.dev/148).
  public var displayName: Swift.String = Swift.String()

  /// Optional. Description of the watchlist.
  public var description: Swift.String = Swift.String()

  /// Optional. Weight applied to the risk score for entities
  /// in this watchlist.
  /// The default is 1.0 if it is not specified.
  public var multiplyingFactor: Swift.Float = Swift.Float()

  /// Required. Mechanism to populate entities in the watchlist.
  public var entityPopulationMechanism: Watchlist.EntityPopulationMechanism? = nil

  /// Output only. Entity count in the watchlist.
  public var entityCount: Watchlist.EntityCount? = nil

  /// Output only. Time the watchlist was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Time the watchlist was last updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Optional. User preferences for watchlist configuration.
  public var watchlistUserPreferences: WatchlistUserPreferences? = nil

  /// Initialize a new instance of `Watchlist`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Watchlist().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Mechanism to populate entities in the watchlist.
  public struct EntityPopulationMechanism: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Ways to populate entities in watchlist.
    /// Currently, only manual is supported.
    public var mechanism: OneOf_Mechanism? = nil

    /// Initialize a new instance of `EntityPopulationMechanism`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = EntityPopulationMechanism().with { $0.manual = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case manual = "manual"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var mechanism: OneOf_Mechanism? = nil
      let mechanismCheckAndSet = {
        if mechanism != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'mechanism'"))
        }
        mechanism = $0
      }
      if let manual = try container.decodeIfPresent(
        Watchlist.EntityPopulationMechanism.Manual?.self, forKey: .manual)
      {
        try mechanismCheckAndSet(.manual(manual))
      }
      self.mechanism = mechanism
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.mechanism {
        switch choice {
        case .manual(let value):
          try container.encode(value, forKey: .manual)
        }
      }
    }

    /// Entities are added manually.
    public struct Manual: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// Initialize a new instance of `Manual`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Manual().with { $0.<placeholder> = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.chronicle.v1.Watchlist.EntityPopulationMechanism.Manual"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    /// Ways to populate entities in watchlist.
    /// Currently, only manual is supported.
    public enum OneOf_Mechanism: Codable, Equatable, Sendable {
      /// Optional. Entities are added manually.
      indirect case manual(Watchlist.EntityPopulationMechanism.Manual?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.chronicle.v1.Watchlist.EntityPopulationMechanism"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Count of different types of entities in the watchlist.
  public struct EntityCount: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Output only. Count of user type entities in the watchlist.
    public var user: Swift.Int32 = Swift.Int32()

    /// Output only. Count of asset type entities in the watchlist.
    public var asset: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `EntityCount`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = EntityCount().with { $0.user = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.chronicle.v1.Watchlist.EntityCount"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.chronicle.v1.Watchlist"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
